source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target 'POI Locator' do
pod 'GoogleMaps', '~> 2.0.1'
pod 'GooglePlaces', '~> 2.0.1'
pod 'SwiftyJSON', '~> 2.3.2'
use_frameworks!
end